name: sharewave
description: "P2P File Transfer App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # HTTP calls
  http: ^1.2.0
  
  # Token save karne ke liye
  shared_preferences: ^2.2.2

  file_picker: ^6.1.1        # ← Yeh add karo
  open_file: ^3.3.2          # ← Download ke baad open karne ke liye
  path_provider: ^2.1.2  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true